service:
  name: currency-data-app

frameworkVersion: ">=1.38.0 <2.0.0"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-2
  environment:
    CURRENCY_DATA_URL: https://prabhath-currency-data.s3-ap-southeast-2.amazonaws.com/currency.json
functions:
  calculateProfit:
    handler: src/currencyExchange.calculateProfit
    events:
      - http:
          path: currency_exchange/calculate/profit
          method: get
          cors: true
